#!/usr/bin/env python3
import sys
import os

import alpine_packages

script_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.join(script_dir, "..", "pylibs"))

import loggy
loggy.enable = True

treepack_repo = os.path.join(script_dir, "treepack_repo")
if os.path.exists(treepack_repo):
    loggy.rmtree(treepack_repo)

packer_repo = os.path.join(script_dir, "packer_repo")

for package in alpine_packages.list:
    package_packer_dir = os.path.join(packer_repo, package, "overlay")
    loggy.run(["treepack", "add",
               "--name", package,
               "--exclude", "lib/apk",
               "--exclude", "etc/apk",
               "--exclude", "var/cache/apk",
               package_packer_dir, treepack_repo])
