#!/usr/bin/env python3

import os
import sys
import argparse

script_dir = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(script_dir, "pylibs"))

import loggy

parser = argparse.ArgumentParser()
parser.add_argument("install_location", help="The directory to download go to")
parser.add_argument("path_dir", help="The directory in PATH to link 'go' to")
args = parser.parse_args()

if not os.path.isdir(args.path_dir):
    sys.exit("Error: path_dir '%s' does not exist" % args.path_dir)

url_path = "https://dl.google.com/go/"
tar_basename = "go1.11.linux-amd64.tar.gz"

print("install_location: %s" % args.install_location)

tar_filename = os.path.join(args.install_location, tar_basename)
if os.path.isfile(tar_filename):
   loggy.remove(tar_filename)

url = url_path + tar_basename
loggy.run(["wget", "-O", tar_filename, url])
loggy.run(["tar", "-C", args.install_location, "-xzf", tar_filename])
loggy.remove(tar_filename)

link_name = os.path.join(args.path_dir, "go")
if os.path.exists(link_name):
    loggy.remove(link_name)
loggy.symlink(os.path.join(args.install_location, "go/bin/go"),
    os.path.join(args.path_dir, "go"))
